#!/bin/sh
#

#
# based on
# https://jeromewu.github.io/build-ffmpeg-webassembly-version-part-2-compile-with-emscripten/ 
#
# would running `emconfigure ./configure arg1 arg2 arg3 ...` do all the magic? no.
# must manually do all these setups.
#









# since the current scriptfile can be referenced from anywhere,
# we'll need to qualify/prefix the SH names with '${BASH_SOURCE[0]}" )'
# 
# examples:
#   "$(dirname -- "${BASH_SOURCE[0]}" )/RegenerateVersionHpp.sh"
#   "$(dirname -- "${BASH_SOURCE[0]}" )/configure"

if test "0" = 1; then
  # verify Emscripten version
  emcc -v
fi

PATH="/ucrt64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
PATH="/j/Dev/emsdk/upstream/emscripten:$PATH"

# configure FFMpeg with Emscripten

# to assign toolchains and extra flags
# see also
# https://github.com/emscripten-core/emscripten/issues/14408 ..
# https://github.com/emscripten-core/emscripten/issues/11985 ..
toolchainSelectingArgs=(
  # 
  --nm=emnm
  --ar=emar
  --ranlib=emranlib
  --cc=emcc
  --cxx=em++
  --objcc=emcc
  --dep-cc=emcc

  # 
  # https://stackoverflow.com/questions/13812185/how-to-recompile-with-fpic 
  # --enable-shared
  --enable-pic

)
# the glag '-fPIC' seema be ignored for WASM targets (presently); there's also offered LD option '--experimental-pic' (on 'wasm-ld')
bincompatClrFlags="    -s LINKABLE -s RELOCATABLE -s SIDE_MODULE -fPIC -Wl,--experimental-pic  "  # a dependency 
bincompatCcFlags=" ${bincompatClrFlags[@]}  "
# systemDepsCcFlags="   -s USE_PTHREADS" # a dependency 
systemDepsCcFlags="   " # a dependency 
rtInitialsFlags=" -s INITIAL_MEMORY=33554432 "
# TODO extend to Obj-C and Obj-C++ 
CFLAGS="     ${CFLAGS[@]}        $bincompatCcFlags $systemDepsCcFlags"  # a dependency 
CXXFLAGS="   ${CXXFLAGS[@]}      $bincompatCcFlags $systemDepsCcFlags"  # a dependency 
# as LDFLAGS. for some reason, LD became 'emcc' which is CC.
LDFLAGS="    ${LDFLAGS[@]}  ${CFLAGS[@]}  $bincompatClrFlags  -fPIC  $rtInitialsFlags     -Wl,--error-limit=270  "  # a dependency 
echo "CFLAGS: ${CFLAGS[@]} "
echo "CXXFLAGS: ${CXXFLAGS[@]} "
echo "LDFLAGS: ${LDFLAGS[@]} "
# LDFLAGS="$CFLAGS -fPIC -s INITIAL_MEMORY=33554432" # 33554432 bytes = 32 MB
echo "toolchainSelectingArgs: ${toolchainSelectingArgs[@]} "

flags=(
  --target-os=none        # use none to prevent any os specific configurations
  --enable-cross-compile  # enable cross compile
  --disable-stripping     # disable stripping
  --arch=x86_32           # use x86_32 to achieve minimal architectural optimization
  # --disable-x86asm        # disable x86 asm
  --disable-asm           # disable asm
  # --disable-inline-asm    # disable inline asm
  --disable-programs            # disable ffmpeg, ffprobe and ffplay build
  # --disable-doc                 # disable doc build
  # --disable-debug               # disable debug mode
  --disable-runtime-cpudetect   # disable cpu detection
  --disable-autodetect          # disable env auto detect

  # assign toolchains and extra flags
  ${toolchainSelectingArgs[@]}
  --extra-cflags="$CFLAGS"
  --extra-cxxflags="$CXXFLAGS"
  --extra-ldflags="$LDFLAGS"
  --extra-ldsoflags="$LDFLAGS"

  # disable thread when FFMPEG_ST is NOT defined
  ${FFMPEG_ST:+ --disable-pthreads --disable-w32threads --disable-os2threads}

  # disable a large number of those less-used codecs
  # we'll eventally reenable some them progressively
  --disable-decoders 
  --disable-encoders
  --disable-muxers
  --disable-demuxers  
  --disable-filters  
  # 
  --enable-decoder=aac             
  --enable-decoder=aac_fixed       
  --enable-decoder=aac_latm        
  --enable-decoder=aasc            
  --enable-decoder=amrnb           
  --enable-decoder=amrwb           
  --enable-decoder=ansi            
  --enable-decoder=ayuv            
  --enable-decoder=cyuv            
  --enable-decoder=flv             
  # --enable-decoder=h261            
  # --enable-decoder=h263            
  # --enable-decoder=h263i           
  # --enable-decoder=h263p           
  --enable-decoder=h264            
  --enable-decoder=huffyuv         
  --enable-decoder=jpeg2000        
  --enable-decoder=jpegls          
  --enable-decoder=magicyuv        
  --enable-decoder=mjpeg           
  --enable-decoder=mjpegb          
  # --enable-decoder=movtext         
  # --enable-decoder=mp1             
  # --enable-decoder=mp1float        
  # --enable-decoder=mp2             
  # --enable-decoder=mp2float        
  --enable-decoder=mp3             
  --enable-decoder=mp3adu          
  --enable-decoder=mp3adufloat     
  --enable-decoder=mp3float        
  --enable-decoder=mp3on4          
  --enable-decoder=mp3on4float     
  --enable-decoder=mpeg1video      
  --enable-decoder=mpeg2video      
  --enable-decoder=mpeg4           
  --enable-decoder=mpegvideo       
  --enable-decoder=opus            
  # --enable-decoder=pcm_alaw        
  # --enable-decoder=pcm_bluray      
  # --enable-decoder=pcm_dvd         
  # --enable-decoder=pcm_f16le       
  # --enable-decoder=pcm_f24le       
  --enable-decoder=pcm_f32be       
  --enable-decoder=pcm_f32le       
  --enable-decoder=pcm_f64be       
  --enable-decoder=pcm_f64le       
  --enable-decoder=pcm_lxf         
  --enable-decoder=pcm_mulaw       
  # --enable-decoder=pcm_s16be       
  # --enable-decoder=pcm_s16be_planar
  # --enable-decoder=pcm_s16le       
  # --enable-decoder=pcm_s16le_planar
  # --enable-decoder=pcm_s24be       
  # --enable-decoder=pcm_s24daud     
  # --enable-decoder=pcm_s24le       
  # --enable-decoder=pcm_s24le_planar
  --enable-decoder=pcm_s32be       
  --enable-decoder=pcm_s32le       
  --enable-decoder=pcm_s32le_planar
  --enable-decoder=pcm_s64be       
  --enable-decoder=pcm_s64le       
  --enable-decoder=pcm_s8          
  --enable-decoder=pcm_s8_planar   
  --enable-decoder=pcm_sga         
  # --enable-decoder=pcm_u16be       
  # --enable-decoder=pcm_u16le       
  # --enable-decoder=pcm_u24be       
  # --enable-decoder=pcm_u24le       
  --enable-decoder=pcm_u32be       
  --enable-decoder=pcm_u32le       
  --enable-decoder=pcm_u8          
  --enable-decoder=pcm_vidc        
  --enable-decoder=pcx             
  --enable-decoder=pgmyuv          
  --enable-decoder=rawvideo        
  --enable-decoder=speedhq         
  --enable-decoder=speex           
  --enable-decoder=tiff            
  --enable-decoder=vorbis          
  # --enable-decoder=vp3             
  # --enable-decoder=vp4             
  # --enable-decoder=vp5             
  # --enable-decoder=vp6             
  # --enable-decoder=vp6a            
  # --enable-decoder=vp6f            
  # --enable-decoder=vp7             
  --enable-decoder=vp8             
  --enable-decoder=vp9             
  # --enable-decoder=vplayer         
  # --enable-decoder=webp            
  # --enable-decoder=yuv4            
  --enable-demuxer=aa              
  --enable-demuxer=aac             
  --enable-demuxer=aax             
  # --enable-demuxer=amr             
  # --enable-demuxer=amrnb           
  # --enable-demuxer=amrwb           
  --enable-demuxer=apng            
  --enable-demuxer=concat          
  --enable-demuxer=flv             
  # --enable-demuxer=h261            
  --enable-demuxer=h263            
  --enable-demuxer=h264            
  --enable-demuxer=image2          
  # --enable-demuxer=image2_alias_pix
  # --enable-demuxer=image2_brender_pix
  --enable-demuxer=image2pipe      
  --enable-demuxer=image_bmp_pipe  
  # --enable-demuxer=image_cri_pipe  
  # --enable-demuxer=image_dds_pipe  
  # --enable-demuxer=image_dpx_pipe  
  # --enable-demuxer=image_exr_pipe  
  # --enable-demuxer=image_gem_pipe  
  --enable-demuxer=image_gif_pipe  
  --enable-demuxer=image_j2k_pipe  
  --enable-demuxer=image_jpeg_pipe 
  # --enable-demuxer=image_jpegls_pipe
  # --enable-demuxer=image_jpegxl_pipe
  # --enable-demuxer=image_pam_pipe  
  # --enable-demuxer=image_pbm_pipe  
  # --enable-demuxer=image_pcx_pipe  
  # --enable-demuxer=image_pfm_pipe  
  # --enable-demuxer=image_pgm_pipe  
  # --enable-demuxer=image_pgmyuv_pipe
  # --enable-demuxer=image_pgx_pipe  
  # --enable-demuxer=image_phm_pipe  
  # --enable-demuxer=image_photocd_pipe
  # --enable-demuxer=image_pictor_pipe
  --enable-demuxer=image_png_pipe  
  --enable-demuxer=image_ppm_pipe  
  --enable-demuxer=image_psd_pipe  
  # --enable-demuxer=image_qdraw_pipe
  # --enable-demuxer=image_qoi_pipe  
  # --enable-demuxer=image_sgi_pipe  
  # --enable-demuxer=image_sunrast_pipe
  # --enable-demuxer=image_svg_pipe  
  # --enable-demuxer=image_tiff_pipe 
  # --enable-demuxer=image_vbn_pipe  
  --enable-demuxer=image_webp_pipe 
  # --enable-demuxer=image_xbm_pipe  
  # --enable-demuxer=image_xpm_pipe  
  # --enable-demuxer=image_xwd_pipe  
  --enable-demuxer=matroska        
  --enable-demuxer=mjpeg           
  --enable-demuxer=mjpeg_2000      
  --enable-demuxer=mov             
  # --enable-demuxer=mp3             
  # --enable-demuxer=mpegps          
  # --enable-demuxer=mpegts          
  # --enable-demuxer=mpegtsraw       
  # --enable-demuxer=mpegvideo       
  --enable-demuxer=mpjpeg          
  --enable-demuxer=ogg             
  # --enable-demuxer=pcm_alaw        
  # --enable-demuxer=pcm_f32be       
  # --enable-demuxer=pcm_f32le       
  # --enable-demuxer=pcm_f64be       
  # --enable-demuxer=pcm_f64le       
  # --enable-demuxer=pcm_mulaw       
  # --enable-demuxer=pcm_s16be       
  # --enable-demuxer=pcm_s16le       
  # --enable-demuxer=pcm_s24be       
  # --enable-demuxer=pcm_s24le       
  # --enable-demuxer=pcm_s32be       
  # --enable-demuxer=pcm_s32le       
  # --enable-demuxer=pcm_s8          
  # --enable-demuxer=pcm_u16be       
  # --enable-demuxer=pcm_u16le       
  # --enable-demuxer=pcm_u24be       
  # --enable-demuxer=pcm_u24le       
  # --enable-demuxer=pcm_u32be       
  # --enable-demuxer=pcm_u32le       
  # --enable-demuxer=pcm_u8          
  # --enable-demuxer=pcm_vidc        
  --enable-demuxer=rawvideo        
  # --enable-demuxer=vobsub          
  # --enable-demuxer=voc             
  # --enable-demuxer=vpk             
  # --enable-demuxer=vplayer         
  --enable-demuxer=webm_dash_manifest
  --enable-demuxer=yuv4mpegpipe    
  --enable-encoder=aac             
  --enable-encoder=ayuv            
  --enable-encoder=flv             
  --enable-encoder=h261            
  --enable-encoder=h263            
  --enable-encoder=h263p           
  # --enable-encoder=huffyuv         
  # --enable-encoder=jpeg2000        
  # --enable-encoder=jpegls          
  # --enable-encoder=magicyuv        
  --enable-encoder=mjpeg           
  # --enable-encoder=movtext         
  # --enable-encoder=mp2             
  # --enable-encoder=mp2fixed        
  # --enable-encoder=mpeg1video      
  # --enable-encoder=mpeg2video      
  --enable-encoder=mpeg4           
  --enable-encoder=opus            
  # --enable-encoder=pcm_alaw        
  # --enable-encoder=pcm_bluray      
  # --enable-encoder=pcm_dvd         
  --enable-encoder=pcm_f32be       
  --enable-encoder=pcm_f32le       
  --enable-encoder=pcm_f64be       
  --enable-encoder=pcm_f64le       
  --enable-encoder=pcm_mulaw       
  # --enable-encoder=pcm_s16be       
  # --enable-encoder=pcm_s16be_planar
  # --enable-encoder=pcm_s16le       
  # --enable-encoder=pcm_s16le_planar
  # --enable-encoder=pcm_s24be       
  # --enable-encoder=pcm_s24daud     
  # --enable-encoder=pcm_s24le       
  # --enable-encoder=pcm_s24le_planar
  --enable-encoder=pcm_s32be       
  --enable-encoder=pcm_s32le       
  --enable-encoder=pcm_s32le_planar
  --enable-encoder=pcm_s64be       
  --enable-encoder=pcm_s64le       
  --enable-encoder=pcm_s8          
  --enable-encoder=pcm_s8_planar   
  # --enable-encoder=pcm_u16be       
  # --enable-encoder=pcm_u16le       
  # --enable-encoder=pcm_u24be       
  # --enable-encoder=pcm_u24le       
  --enable-encoder=pcm_u32be       
  --enable-encoder=pcm_u32le       
  --enable-encoder=pcm_u8          
  --enable-encoder=pcm_vidc        
  --enable-encoder=pcx             
  # --enable-encoder=pgmyuv          
  --enable-encoder=rawvideo        
  # --enable-encoder=speedhq         
  --enable-encoder=tiff            
  --enable-encoder=vorbis          
  --enable-encoder=yuv4           
  --enable-muxer=amr               
  --enable-muxer=apng              
  --enable-muxer=flv               
  --enable-muxer=h261              
  --enable-muxer=h263              
  --enable-muxer=h264              
  --enable-muxer=image2            
  --enable-muxer=image2pipe        
  --enable-muxer=matroska          
  --enable-muxer=matroska_audio    
  --enable-muxer=mjpeg             
  --enable-muxer=mkvtimestamp_v2   
  --enable-muxer=mov               
  --enable-muxer=mp2               
  --enable-muxer=mp3               
  --enable-muxer=mp4               
  # --enable-muxer=mpeg1system       
  # --enable-muxer=mpeg1vcd          
  # --enable-muxer=mpeg1video        
  # --enable-muxer=mpeg2dvd          
  # --enable-muxer=mpeg2svcd         
  # --enable-muxer=mpeg2video        
  # --enable-muxer=mpeg2vob          
  # --enable-muxer=mpegts            
  --enable-muxer=mpjpeg            
  --enable-muxer=null            
  --enable-muxer=ogg               
  --enable-muxer=ogv               
  --enable-muxer=opus              
  # --enable-muxer=pcm_alaw          
  # --enable-muxer=pcm_f32be         
  # --enable-muxer=pcm_f32le         
  # --enable-muxer=pcm_f64be         
  # --enable-muxer=pcm_f64le         
  # --enable-muxer=pcm_mulaw         
  # --enable-muxer=pcm_s16be         
  # --enable-muxer=pcm_s16le         
  # --enable-muxer=pcm_s24be         
  # --enable-muxer=pcm_s24le         
  # --enable-muxer=pcm_s32be         
  # --enable-muxer=pcm_s32le         
  # --enable-muxer=pcm_s8            
  # --enable-muxer=pcm_u16be         
  # --enable-muxer=pcm_u16le         
  # --enable-muxer=pcm_u24be         
  # --enable-muxer=pcm_u24le         
  # --enable-muxer=pcm_u32be         
  # --enable-muxer=pcm_u32le         
  # --enable-muxer=pcm_u8            
  # --enable-muxer=pcm_vidc          
  --enable-muxer=rawvideo          
  --enable-muxer=voc               
  --enable-muxer=webm              
  --enable-muxer=webm_chunk        
  --enable-muxer=webm_dash_manifest
  --enable-muxer=webp              
  --enable-muxer=yuv4mpegpipe       
  # # --enable-filter=abench           
  # # --enable-filter=abitscope        
  # --enable-filter=acompressor      
  # # --enable-filter=acontrast        
  --enable-filter=acopy            
  # --enable-filter=acrossfade       
  # --enable-filter=acrossover       
  # --enable-filter=acrusher         
  # --enable-filter=acue             
  # --enable-filter=addroi           
  # --enable-filter=adeclick         
  # --enable-filter=adeclip          
  # --enable-filter=adecorrelate     
  --enable-filter=adelay           
  # --enable-filter=adenorm          
  # --enable-filter=aderivative      
  # --enable-filter=adrawgraph       
  # --enable-filter=adynamicequalizer
  # --enable-filter=adynamicsmooth   
  # --enable-filter=aecho            
  # --enable-filter=aemphasis        
  # --enable-filter=aeval            
  # --enable-filter=aevalsrc         
  # --enable-filter=aexciter         
  --enable-filter=afade            
  # --enable-filter=afftdn           
  # --enable-filter=afftfilt         
  # --enable-filter=afifo            
  # --enable-filter=afir             
  # --enable-filter=afirsrc          
  --enable-filter=aformat          
  # --enable-filter=afreqshift       
  # --enable-filter=afwtdn           
  # --enable-filter=agate            
  # --enable-filter=agraphmonitor    
  # --enable-filter=ahistogram       
  # --enable-filter=aiir             
  # --enable-filter=aintegral        
  --enable-filter=ainterleave      
  # --enable-filter=alatency         
  # --enable-filter=alimiter         
  # --enable-filter=allpass          
  --enable-filter=allrgb           
  --enable-filter=allyuv           
  --enable-filter=aloop            
  --enable-filter=alphaextract     
  --enable-filter=alphamerge       
  --enable-filter=amerge           
  --enable-filter=ametadata        
  # --enable-filter=amix             
  # --enable-filter=amovie  # technically redundant, 'movie' can be explicitly (re)configured to select 'a's
  # --enable-filter=amplify          
  # --enable-filter=amultiply        
  # --enable-filter=anequalizer      
  # --enable-filter=anlmdn           
  # --enable-filter=anlmf            
  # --enable-filter=anlms            
  # --enable-filter=anoisesrc        
  --enable-filter=anull            
  --enable-filter=anullsink        
  --enable-filter=anullsrc         
  # --enable-filter=apad             
  # --enable-filter=aperms           
  # --enable-filter=aphasemeter      
  # --enable-filter=aphaser          
  # --enable-filter=aphaseshift      
  # --enable-filter=apsyclip         
  # --enable-filter=apulsator        
  --enable-filter=arealtime        
  --enable-filter=aresample        
  --enable-filter=areverse         
  # --enable-filter=arnndn           
  # --enable-filter=asdr             
  --enable-filter=asegment         
  --enable-filter=aselect          
  --enable-filter=asendcmd         
  # --enable-filter=asetnsamples     
  # --enable-filter=asetpts          
  # --enable-filter=asetrate         
  # --enable-filter=asettb           
  # --enable-filter=ashowinfo        
  # --enable-filter=asidedata        
  # --enable-filter=asoftclip        
  # --enable-filter=aspectralstats   
  --enable-filter=asplit           
  --enable-filter=astats           
  --enable-filter=astreamselect    
  # --enable-filter=asubboost        
  # --enable-filter=asubcut          
  # --enable-filter=asupercut        
  # --enable-filter=asuperpass       
  # --enable-filter=asuperstop       
  # --enable-filter=atadenoise       
  --enable-filter=atempo           
  # --enable-filter=atilt            
  # --enable-filter=atrim            
  # --enable-filter=avectorscope     
  --enable-filter=avgblur          
  # --enable-filter=avsynctest       
  # --enable-filter=axcorrelate      
  # --enable-filter=bandpass         
  # --enable-filter=bandreject       
  # --enable-filter=bass             
  --enable-filter=bbox             
  # --enable-filter=bench            
  # --enable-filter=bilateral        
  # --enable-filter=biquad           
  # --enable-filter=bitplanenoise    
  # --enable-filter=blend            
  # --enable-filter=bm3d             
  # --enable-filter=bwdif            
  # --enable-filter=cas              
  # --enable-filter=cellauto         
  --enable-filter=channelmap       
  --enable-filter=channelsplit     
  # --enable-filter=chorus           
  # --enable-filter=chromahold       
  # --enable-filter=chromakey        
  # --enable-filter=chromanr         
  # --enable-filter=chromashift      
  # --enable-filter=ciescope         
  # --enable-filter=codecview        
  --enable-filter=color            
  # --enable-filter=colorbalance     
  # --enable-filter=colorchannelmixer
  # --enable-filter=colorchart       
  # --enable-filter=colorcontrast    
  # --enable-filter=colorcorrect     
  # --enable-filter=colorhold        
  # --enable-filter=colorize         
  # --enable-filter=colorkey         
  # --enable-filter=colorlevels      
  # --enable-filter=colormap         
  # --enable-filter=colorspace       
  # --enable-filter=colorspectrum    
  # --enable-filter=colortemperature 
  # --enable-filter=compand          
  # --enable-filter=compensationdelay
  --enable-filter=concat           
  # --enable-filter=convolution      
  # --enable-filter=convolve         
  --enable-filter=copy             
  --enable-filter=crop             
  # --enable-filter=crossfeed        
  # --enable-filter=crystalizer      
  # --enable-filter=cue              
  # --enable-filter=curves           
  # --enable-filter=datascope        
  # --enable-filter=dblur            
  # --enable-filter=dcshift          
  # --enable-filter=dctdnoiz         
  # --enable-filter=dialoguenhance   
  # --enable-filter=dilation         
  # --enable-filter=displace         
  # --enable-filter=doubleweave      
  --enable-filter=drawbox          
  --enable-filter=drawgraph        
  --enable-filter=drawgrid         
  # --enable-filter=drmeter          
  # --enable-filter=dynaudnorm       
  # --enable-filter=earwax           
  # --enable-filter=ebur128          
  # --enable-filter=elbg             
  # --enable-filter=entropy          
  # --enable-filter=epx              
  --enable-filter=equalizer        
  # --enable-filter=erosion          
  # --enable-filter=estdif           
  # --enable-filter=exposure         
  --enable-filter=extractplanes    
  # --enable-filter=extrastereo      
  --enable-filter=fade             
  # --enable-filter=feedback         
  # --enable-filter=fftdnoiz         
  # --enable-filter=fftfilt          
  # --enable-filter=field            
  # --enable-filter=fieldhint        
  # --enable-filter=fieldmatch       
  # --enable-filter=fieldorder       
  # --enable-filter=fifo             
  # --enable-filter=fillborders      
  # --enable-filter=firequalizer     
  # --enable-filter=flanger          
  # --enable-filter=floodfill        
  --enable-filter=format           
  --enable-filter=fps              
  # --enable-filter=framepack        
  --enable-filter=framerate        
  --enable-filter=framestep        
  --enable-filter=freezeframes     
  # --enable-filter=gblur            
  # --enable-filter=geq              
  # --enable-filter=gradfun          
  # --enable-filter=gradients        
  # --enable-filter=graphmonitor     
  # --enable-filter=grayworld        
  # --enable-filter=greyedge         
  # --enable-filter=guided           
  # # --enable-filter=haas             
  # # --enable-filter=haldclut         
  # # --enable-filter=haldclutsrc      
  # # --enable-filter=hdcd             
  # # --enable-filter=headphone        
  # --enable-filter=hflip            
  --enable-filter=highpass         
  # --enable-filter=highshelf        
  # --enable-filter=hilbert          
  # --enable-filter=histogram        
  --enable-filter=hqx              
  # --enable-filter=hstack           
  # --enable-filter=hsvhold          
  # --enable-filter=hsvkey           
  --enable-filter=hue              
  --enable-filter=huesaturation    
  # --enable-filter=hwdownload       
  # --enable-filter=hwmap            
  # --enable-filter=hwupload         
  # --enable-filter=hysteresis       
  # --enable-filter=identity         
  # --enable-filter=idet             
  # --enable-filter=il               
  # --enable-filter=inflate          
  # --enable-filter=interleave       
  --enable-filter=join             
  # # --enable-filter=kirsch           
  # # --enable-filter=lagfun           
  --enable-filter=latency          
  # --enable-filter=lenscorrection   
  # --enable-filter=life             
  # --enable-filter=limitdiff        
  # --enable-filter=limiter          
  --enable-filter=loop             
  # --enable-filter=loudnorm         
  --enable-filter=lowpass          
  # --enable-filter=lowshelf         
  # --enable-filter=lumakey          
  # --enable-filter=lut              
  # --enable-filter=lut1d            
  # --enable-filter=lut2             
  # --enable-filter=lut3d            
  # --enable-filter=lutrgb           
  # --enable-filter=lutyuv           
  # --enable-filter=mandelbrot       
  # --enable-filter=mcompand         
  # --enable-filter=median           
  --enable-filter=mergeplanes      
  # --enable-filter=mestimate        
  --enable-filter=metadata         
  # --enable-filter=midequalizer     
  # --enable-filter=minterpolate     
  --enable-filter=mix              
  --enable-filter=monochrome       
  # # --enable-filter=morpho           
  --enable-filter=movie            
  # --enable-filter=msad             
  --enable-filter=multiply         
  # --enable-filter=negate           
  # --enable-filter=nlmeans          
  --enable-filter=noformat         
  # --enable-filter=noise            
  # --enable-filter=normalize        
  --enable-filter=null             
  --enable-filter=nullsink         
  --enable-filter=nullsrc          
  # --enable-filter=oscilloscope     
  --enable-filter=overlay          
  --enable-filter=pad              
  # --enable-filter=pal100bars       
  # --enable-filter=pal75bars        
  # --enable-filter=palettegen       
  # --enable-filter=paletteuse       
  # --enable-filter=pan              
  # --enable-filter=perms            
  # --enable-filter=photosensitivity 
  # --enable-filter=pixdesctest      
  # --enable-filter=pixelize         
  # --enable-filter=pixscope         
  --enable-filter=premultiply      
  # --enable-filter=prewitt          
  # --enable-filter=pseudocolor      
  # --enable-filter=psnr             
  # --enable-filter=qp               
  --enable-filter=random           
  # --enable-filter=readeia608       
  # --enable-filter=readvitc         
  --enable-filter=realtime         
  --enable-filter=remap            
  # --enable-filter=removegrain      
  # --enable-filter=removelogo       
  # --enable-filter=replaygain       
  # --enable-filter=reverse          
  --enable-filter=rgbashift        
  --enable-filter=rgbtestsrc       
  # --enable-filter=roberts          
  # --enable-filter=rotate           
  --enable-filter=scale            
  --enable-filter=scale2ref        
  # --enable-filter=scdet            
  # --enable-filter=scharr           
  # --enable-filter=scroll           
  # --enable-filter=segment          
  --enable-filter=select           
  # --enable-filter=selectivecolor   
  # --enable-filter=sendcmd          
  # --enable-filter=separatefields   
  --enable-filter=setdar           
  # --enable-filter=setfield         
  --enable-filter=setparams        
  --enable-filter=setpts           
  --enable-filter=setrange         
  --enable-filter=setsar           
  --enable-filter=settb            
  # --enable-filter=shear            
  # --enable-filter=showcqt          
  # --enable-filter=showfreqs        
  # --enable-filter=showinfo         
  # --enable-filter=showpalette      
  # --enable-filter=showspatial      
  --enable-filter=showspectrum     
  --enable-filter=showspectrumpic  
  # --enable-filter=showvolume       
  # --enable-filter=showwaves        
  # --enable-filter=showwavespic     
  # --enable-filter=shuffleframes    
  # --enable-filter=shufflepixels    
  # --enable-filter=shuffleplanes    
  # --enable-filter=sidechaincompress
  # --enable-filter=sidechaingate    
  # --enable-filter=sidedata         
  # --enable-filter=sierpinski       
  # --enable-filter=signalstats      
  # --enable-filter=silenceremove    
  --enable-filter=sinc             
  --enable-filter=sine             
  # --enable-filter=siti             
  # --enable-filter=smptebars        
  # --enable-filter=smptehdbars      
  # --enable-filter=sobel            
  --enable-filter=spectrumsynth    
  # --enable-filter=speechnorm       
  --enable-filter=split            
  # --enable-filter=sr               
  # --enable-filter=ssim             
  # --enable-filter=stereotools      
  # --enable-filter=stereowiden      
  --enable-filter=streamselect     
  --enable-filter=superequalizer   
  --enable-filter=surround         
  --enable-filter=swaprect         
  --enable-filter=swapuv           
  # --enable-filter=tblend           
  # --enable-filter=telecine         
  --enable-filter=testsrc          
  --enable-filter=testsrc2         
  # --enable-filter=thistogram       
  # --enable-filter=threshold        
  # --enable-filter=thumbnail        
  # --enable-filter=tile             
  # --enable-filter=tiltshelf        
  # --enable-filter=tlut2            
  # --enable-filter=tmedian          
  # --enable-filter=tmidequalizer    
  # --enable-filter=tmix             
  # --enable-filter=tonemap          
  # --enable-filter=tpad             
  # --enable-filter=transpose        
  # --enable-filter=treble           
  # --enable-filter=tremolo          
  # --enable-filter=trim             
  --enable-filter=unpremultiply    
  # --enable-filter=unsharp          
  # --enable-filter=untile           
  # --enable-filter=v360             
  # --enable-filter=varblur          
  # --enable-filter=vectorscope      
  --enable-filter=vflip            
  # --enable-filter=vfrdet           
  # --enable-filter=vibrance         
  # --enable-filter=vibrato          
  # --enable-filter=vif              
  # --enable-filter=vignette         
  # --enable-filter=virtualbass      
  # --enable-filter=vmafmotion       
  --enable-filter=volume           
  # --enable-filter=vstack           
  # --enable-filter=w3fdif           
  --enable-filter=waveform         
  # --enable-filter=weave            
  # --enable-filter=xbr              
  # --enable-filter=xcorrelate       
  # --enable-filter=xfade            
  # --enable-filter=xmedian          
  # --enable-filter=xstack           
  # --enable-filter=yadif            
  # --enable-filter=yaepblur         
  --enable-filter=yuvtestsrc       
  --enable-filter=zoompan          
)
test "0" = "1" && echo "flags:" ${flags[@]}
test "0" = "1" && exit 1

# now direct to the main thing
x_configureshfile="$(dirname -- "${BASH_SOURCE[0]}" )/configure"
if test "0" = 1; then
  emconfigure "$x_configureshfile" "${flags[@]}"
else
  $x_configureshfile "${flags[@]}"
fi





