#!/bin/sh
#










# since the current scriptfile can be referenced from anywhere,
# we'll need to qualify/prefix the SH names with '${BASH_SOURCE[0]}" )', or instead
# switch WD to this dir

# basing these build steps on what `INSTALL.md` says

# PATH="/ucrt64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
# PATH="/j/Dev/emsdk/upstream/emscripten:$PATH"
PATH="$("$(dirname -- "${BASH_SOURCE[0]}" )/with-emsdk" )"

cd "$(dirname -- "${BASH_SOURCE[0]}" )"

{ make ; } || { echo "'make' failed; exiting early " ; exit 1 ; }






{ ./makebuild-aftermath-emb ; } || { echo "'./makebuild-aftermath-emb' failed; exiting early " ; exit 1 ; }






node ./build/ff-ranwithemcp/ffmpeg.js -loglevel verbose -f lavfi -i testsrc2=duration=5.1 -f null -c:v rawvideo myvideo











